data:
  _target_: shimnet.generators.Generator
  input_normalization_height: 16.0
  clean_spectra_generator:
    _target_: shimnet.generators.TheoreticalMultipletSpectraGenerator
    pixels: 2048
    frq_step: ${metadata.frq_step}
    peaks_parameter_generator:
      _target_: shimnet.generators.MultipletDataFromMultipletsLibrary
      number_of_signals_min: 2 # null to use all signals (both min and max must be null)
      number_of_signals_max: 10 # null to use all signals (both min and max must be null)
      use_original_peak_position: false
      relative_frequency_min: -0.4
      relative_frequency_max: 0.4
      multiplet_height_factor_min: 0.5
      multiplet_height_factor_max: 2
      multiplet_width_factor_min: 0.5
      multiplet_width_factor_max: 2
      multiplets_library:
        _target_: shimnet.generators.MultipletsLibrary
        csv_files_paths:
        - data/multiplets_lists/azydekbenzylu_sub1_mono-click.csv
        - data/multiplets_lists/fenyloacetylen_sub2_mono-click.csv
        - data/multiplets_lists/mieszanina_poReakcji_mono-click.csv
        peak_data_parser:
          _target_: shimnet.generators.PeaksParametersParser
      seed: null
  response_generator:
    _target_: shimnet.generators.ResponseGenerator
    response_function_library:
      _target_: shimnet.generators.ResponseLibrary
      response_files:
      - data/scrf_81_600MHz.pt
  noise_generator:
    _target_: shimnet.generators.NoiseGenerator
    spectrum_noise_min: 0.0
    spectrum_noise_max: 0.1
  include_spectrum_data: false
  include_peak_mask: false
  include_response_function: true
  seed: 44 # null means random seed
  batch_size: null # to be set in training script
metadata:
  frq_step: 0.30048
  spectrometer_frequency: 600.0